apiVersion: v1
kind: Service
metadata:
  labels:
    run: db-api
  name: db-api
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    run: db-api
status:
  loadBalancer: {}
