---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-claim-peer0-medutils-manufacturer
spec:
  volumeName: pv-couchdb-claim-peer0-medutils-manufacturer
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
