---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthprods-peer0-manufacturer-disk-claim
spec:
  volumeName: pv-healthprods-peer0-manufacturer-disk-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
