---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-orderer-manufacturer
spec:
  volumeName: pv-orderer-manufacturer
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: files
