---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: disk-claim-medutils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5G
