---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ministry-of-health-disk-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
