---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-claim-peer0-medutils
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
