---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-hospital-of-athens-proxy-admin-cli-common
spec:
  replicas: 1
  selector:
    matchLabels:
      app: general-hospital-of-athens-proxy-admin-cli-common
  template:
    metadata:
      labels:
        app: general-hospital-of-athens-proxy-admin-cli-common
    spec:
      containers:
        - name: main
          image: hyperledger/fabric-tools:{{FABRIC_VERSION}}
          imagePullPolicy: IfNotPresent
          env:
            - name: FABRIC_CFG_PATH
              value: /var/hyperledger/fabric/config/proxy
            - name: FABRIC_CA_SERVER_HOME
              value: "/var/hyperledger/ca-general-hospital-of-athens-server"
            - name: FABRIC_CA_CLIENT_HOME
              value: "/var/hyperledger/ca-general-hospital-of-athens-client"
          args:
            - sleep
            - "2147483647"
          workingDir: /
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config/proxy
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: disk-claim-general-hospital-of-athens
        - name: fabric-config
          configMap:
            name: general-hospital-of-athens-proxy-config
