"use strict";
const REQUEST_LOG = "REQUEST_LOG";
const UPDATE_LOG = "UPDATE_LOG";

module.exports = Object.freeze({
    logs: "logs",
    REQUEST_LOG: REQUEST_LOG,
    UPDATE_LOG: UPDATE_LOG,
    RETRIEVE_LOG_REQUEST: "RETRIEVE_LOG_REQUEST",
    AVAILABLE_REQUEST_TYPES: [REQUEST_LOG, UPDATE_LOG],
    AVAILABLE_DOMAINS: ["PROXY", "MEDICAL", "MANUFACTURER"],
});
