apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  enabled_plugins: |
    [rabbitmq_federation,rabbitmq_management,rabbitmq_peer_discovery_k8s].
  rabbitmq.conf: |
    loopback_users.guest = false
    listeners.tcp.default = 5672
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname

    cluster_formation.node_cleanup.only_log_warning = true


    listeners.ssl.default = 5671

    ssl_options.cacertfile = /config/ssl/ca.crt
    ssl_options.certfile   = /config/ssl/tls.crt
    ssl_options.keyfile    = /config/ssl/tls.key
    ssl_options.verify     = verify_peer
    ssl_options.fail_if_no_peer_cert = true
