---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-orderer-medical
spec:
  volumeName: pv-orderer-medical
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: files
