---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attikon-hospital-peer0-medical-disk-claim
spec:
  volumeName: pv-attikon-hospital-peer0-medical-disk-claim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 5Gi
