#!/bin/sh

set -euo pipefail

CHAINCODE_SOURCE_DIR=$1
CHAINCODE_METADATA_DIR="$2"
BUILD_OUTPUT_DIR=$3

# External chaincodes expect connection.json file in the chaincode package
if [ ! -f "$CHAINCODE_SOURCE_DIR/connection.json" ]; then
    echo >&2 "$CHAINCODE_SOURCE_DIR/connection.json not found"
    exit 1
fi

echo >&2 "$(cat $CHAINCODE_SOURCE_DIR/connection.json)"

# Simply copy the endpoint information to the specified output location
mkdir -p $BUILD_OUTPUT_DIR/chaincode/
echo "$(cat $CHAINCODE_SOURCE_DIR/connection.json)" >$BUILD_OUTPUT_DIR/chaincode/connection.json

if [ -d "$CHAINCODE_SOURCE_DIR/metadata" ]; then
    echo "$(cat $CHAINCODE_SOURCE_DIR/metadata)" >$BUILD_OUTPUT_DIR/chaincode/metadata
fi

if [ -d "$CHAINCODE_SOURCE_DIR/META-INF" ]; then
    cp -a "$CHAINCODE_SOURCE_DIR/META-INF" "$BUILD_OUTPUT_DIR/chaincode/"
fi

exit 0
