#!/bin/sh

CHAINCODE_METADATA_DIR="$2"

TYPE=$(tr -d '\n' <"$CHAINCODE_METADATA_DIR/metadata.json" | awk -F':' '{ for (i = 1; i < NF; i++){ if ($i~/type/) { print $(i+1); break }}}' | cut -d\" -f2)
if [ "$TYPE" = "external" ]; then
    exit 0
fi

exit 1
