#!/bin/sh

set -euo pipefail

BUILD_OUTPUT_DIR="$1"
RELEASE_OUTPUT_DIR="$2"

if [ -d "$BUILD_OUTPUT_DIR/chaincode/META-INF" ]; then
   # mkdir -p "$RELEASE_OUTPUT_DIR/chaincode/server"
   cp -a "$BUILD_OUTPUT_DIR/chaincode/META-INF/"* "$RELEASE_OUTPUT_DIR/"
fi

# External chaincodes expect artifacts to be placed under "$RELEASE_OUTPUT_DIR"/chaincode/server
if [ -f $BUILD_OUTPUT_DIR/chaincode/connection.json ]; then
   mkdir -p "$RELEASE_OUTPUT_DIR/chaincode/server/tls"
   echo "$(cat $BUILD_OUTPUT_DIR/chaincode/connection.json)" >"$RELEASE_OUTPUT_DIR"/chaincode/server/connection.json
   # If tls_required is true, copy TLS files (using above example, the fully qualified path for these fils would be "$RELEASE_OUTPUT_DIR"/chaincode/server/tls)

   echo "$(tr -d '\n' <"$BUILD_OUTPUT_DIR/chaincode/connection.json" | awk -F':' '{ for (i = 1; i < NF; i++){ if ($i~/client_cert/) { print $(i+1); break }}}' | cut -d\" -f2)" >"$RELEASE_OUTPUT_DIR"/chaincode/server/client.crt
   echo "$(tr -d '\n' <"$BUILD_OUTPUT_DIR/chaincode/connection.json" | awk -F':' '{ for (i = 1; i < NF; i++){ if ($i~/client_key/) { print $(i+1); break }}}' | cut -d\" -f2)" >"$RELEASE_OUTPUT_DIR"/chaincode/server/client.key
   echo "$(tr -d '\n' <"$BUILD_OUTPUT_DIR/chaincode/connection.json" | awk -F':' '{ for (i = 1; i < NF; i++){ if ($i~/root_cert/) { print $(i+1); break }}}' | cut -d\" -f2)" >"$RELEASE_OUTPUT_DIR"/chaincode/server/root.crt

   exit 0
fi

exit 1
