"use strict";

module.exports = Object.freeze({
    STAKEHOLDER_BALLOT: "STAKEHOLDER_VOTING",
    ELECTIONS: "ELECTIONS",
    ACTIVE_ELECTION: "ACTIVE_ELECTION",
    COMPLETED_ELECTION: "COMPLETED_ELECTIONS",
    COMPLETED_ELECTIONS_STAKEHOLDER: "COMPLETED_ELECTIONS_STAKEHOLDER",
    ACCEPTABLE_ELECTION_TYPES: ["add_ca", "remove_ca", "logs"],
});
