apiVersion: v1
kind: ConfigMap
metadata:
  name: cc-{{ CHAINCODE_NAME }}-{{ CHAINCODE_ORGANIZATION }}-env
data:
  CHAINCODE_CCID: { { CHAINCODE_CCID } }
  CHAINCODE_ADDRESS: cc-{{ CHAINCODE_NAME }}-{{ CHAINCODE_ORGANIZATION }}
  CHAINCODE_LISTEN_ADDRESS: "0.0.0.0"
  CHAINCODE_PORT: "9999"
  TLS_CA_CERT_PATH: /var/hyperledger/fabric/organizations/peerOrganizations/{{ CHAINCODE_ORGANIZATION }}/chaincodes/cc-{{ CHAINCODE_ORGANIZATION }}-{{ CHAINCODE_NAME }}@{{ CHAINCODE_ORGANIZATION }}/tls/cacerts/ca-{{ CHAINCODE_ORGANIZATION }}.pem
  TLS_CERT_PATH: /var/hyperledger/fabric/organizations/peerOrganizations/{{ CHAINCODE_ORGANIZATION }}/chaincodes/cc-{{ CHAINCODE_ORGANIZATION }}-{{ CHAINCODE_NAME }}@{{ CHAINCODE_ORGANIZATION }}/tls/signcerts/cert.pem
  TLS_CERT_KEY_PATH: /var/hyperledger/fabric/organizations/peerOrganizations/{{ CHAINCODE_ORGANIZATION }}/chaincodes/cc-{{ CHAINCODE_ORGANIZATION }}-{{ CHAINCODE_NAME }}@{{ CHAINCODE_ORGANIZATION }}/tls/keystore/server.key
  TZ: Europe/Athens
