---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medutils-manufacturer-admin-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medutils-manufacturer-admin-cli
  template:
    metadata:
      labels:
        app: medutils-manufacturer-admin-cli
    spec:
      containers:
        - name: main
          image: hyperledger/fabric-tools:{{FABRIC_VERSION}}
          imagePullPolicy: IfNotPresent
          env:
            - name: FABRIC_CFG_PATH
              value: /var/hyperledger/fabric/config/manufacturer
            - name: CORE_PEER_MSPCONFIGPATH
              value: /var/hyperledger/fabric/organizations/peerOrganizations/medutils/users/medutils-generaladmin@medutils/msp
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /var/hyperledger/fabric/organizations/peerOrganizations/medutils/msp/tlscacerts/ca-medutils.pem
          args:
            - sleep
            - "2147483647"
          workingDir: /root
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config/manufacturer

      # This init container will unfurl all of the MSP archives listed in the msp-config config map.
      initContainers:
        - name: msp-unfurl
          image: busybox
          command:
            - sh
            - -c
            - "for msp in $(ls /msp/manufacturer/msp-*.tgz); do echo $msp && tar zxvf $msp -C /var/hyperledger/fabric; done"
          volumeMounts:
            - name: msp-config
              mountPath: /msp/manufacturer
            - name: fabric-volume
              mountPath: /var/hyperledger
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: disk-claim-medutils
        - name: fabric-config
          configMap:
            name: medutils-manufacturer-config
        - name: msp-config
          configMap:
            name: msp-config-manufacturer
