apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-medutils
  labels:
    app: ca-medutils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-medutils
  template:
    metadata:
      labels:
        app: ca-medutils
    spec:
      volumes:
        - name: ca-config
          configMap:
            name: ca-config-medutils
        - name: ca-files
          persistentVolumeClaim:
            claimName: disk-claim-medutils
      containers:
        - name: main
          image: hyperledger/fabric-ca:1.5.2
          env:
            - name: FABRIC_CA_SERVER_HOME
              value: "/var/hyperledger/ca-medutils-server"
            - name: FABRIC_CA_CLIENT_HOME
              value: "/var/hyperledger/ca-medutils-client"
            # - name: FABRIC_CA_SERVER_TLS_CERTFILE
            #   value: "/var/hyperledger/ca-medutils-client/tls-ca/rcadminorg2/msp/signcerts/cert.pem"
            # - name: FABRIC_CA_SERVER_TLS_KEYFILE
            #   value: "/var/hyperledger/ca-medutils-client/tls-ca/rcadminorg2/msp/keystore/key.pem"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - name: ca-files
              mountPath: /var/hyperledger
            - name: ca-config
              mountPath: /var/hyperledger/ca-medutils-server/fabric-ca-server-config.yaml
              subPath: ca-config-medutils.yaml
          ports:
            - containerPort: 443
          # readinessProbe:
          #   tcpSocket:
          #     port: 443
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ca-medutils
  labels:
    app: ca-medutils
spec:
  selector:
    app: ca-medutils
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
