apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-ministry-of-health
  labels:
    app: ca-ministry-of-health
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-ministry-of-health
  template:
    metadata:
      labels:
        app: ca-ministry-of-health
    spec:
      volumes:
        - name: ca-config
          configMap:
            name: ca-config-ministry-of-health
        - name: ca-files
          persistentVolumeClaim:
            claimName: ministry-of-health-disk-claim
      containers:
        - name: main
          image: hyperledger/fabric-ca:1.5.2
          env:
            - name: FABRIC_CA_SERVER_HOME
              value: "/var/hyperledger/ca-ministry-of-health-server"
            - name: FABRIC_CA_CLIENT_HOME
              value: "/var/hyperledger/ca-ministry-of-health-client"
            # - name: FABRIC_CA_SERVER_TLS_CERTFILE
            #   value: "/var/hyperledger/ca-ministry-of-health-client/tls-ca/rcaadminminofhealth/msp/signcerts/cert.pem"
            # - name: FABRIC_CA_SERVER_TLS_KEYFILE
            #   value: "/var/hyperledger/ca-ministry-of-health-client/tls-ca/rcaadminminofhealth/msp/keystore/key.pem"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - name: ca-files
              mountPath: /var/hyperledger
            - name: ca-config
              mountPath: /var/hyperledger/ca-ministry-of-health-server/fabric-ca-server-config.yaml
              subPath: ca-config-ministry-of-health.yaml
          ports:
            - containerPort: 443
          # readinessProbe:
          #   tcpSocket:
          #     port: 443
          #   initialDelaySeconds: 2
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ca-ministry-of-health
  labels:
    app: ca-ministry-of-health
spec:
  selector:
    app: ca-ministry-of-health
  ports:
    - protocol: TCP
      name: tls
      port: 443
      targetPort: 443
