apiVersion: v1
kind: Service
metadata:
  labels:
    run: dbc-api
  name: dbc-api
spec:
  type: NodePort
  ports:
    - name: "5005"
      port: 5005
      targetPort: 5005
      nodePort: 32200
      
  selector:
    run: dbc-api
status:
  loadBalancer: {}
