module.exports = Object.freeze({
    INFRASTRUCTURE_ENDPOINT: process.env.REACT_APP_INFRASTRUCTURE_ENDPOINT,

    LOGIN_ENDPOINT: process.env.REACT_APP_BACKEND_API_LOGIN_ENDPOINT,

    REFRESH_TOKEN_ENDPOINT:
        process.env.REACT_APP_BACKEND_API_REFRESH_TOKEN_ENDPOINT,

    LOGOUT_ENDPOINT: process.env.REACT_APP_BACKEND_API_LOGOUT_ENDPOINT,

    REGISTER_USER_ENDPOINT:
        process.env.REACT_APP_BACKEND_API_REGISTER_USER_ENDPOINT,

    USER_VALIDATION_ENDPOINT:
        process.env.REACT_APP_BACKEND_API_USER_VALIDATION_ENDPOINT,

    RETRIEVE_LOG_INIT_ENDPOINT:
        process.env.REACT_APP_BACKEND_API_RETRIEVE_LOG_INIT_ENDPOINT,

    RETRIEVE_LOGS_ENDPOINT:
        process.env.REACT_APP_BACKEND_API_RETRIEVE_LOGS_ENDPOINT,

    SYNC_AUDITS_ENDPOINT: process.env.REACT_APP_BACKEND_SYNC_AUDITS_ENDPOINT,

    SYNC_WITH_BC_ENDPOINT:
        process.env.REACT_APP_BACKEND_API_SYNC_WITH_BC_ENDPOINT,

    SYNC_WITH_BC_STAKEHOLDER_ELECTIONS_ENDPOINT:
        process.env
            .REACT_APP_BACKEND_API_SYNC_WITH_BC_STAKEHOLDER_ELECTIONS_ENDPOINT,

    SYNC_WITH_BC_ELECTION_EXTRA_INFO_ENDPOINT:
        process.env
            .REACT_APP_BACKEND_API_SYNC_WITH_BC_ELECTION_EXTRA_INFO_ENDPOINT,

    GET_DATA_FROM_BC_ENDPOINT: process.env.REACT_APP_GET_DATA_FROM_BC_ENDPOINT,

    UPDATE_TRUST_ANCHORS_ENDPOINT:
        process.env.REACT_APP_UPDATE_TRUST_ANCHORS_ENDPOINT,

    VOTE_ENDPOINT: process.env.REACT_APP_VOTE_ENDPOINT,
    ADD_CA_ENDPOINT: process.env.REACT_APP_ADD_CA_ENDPOINT,

    REMOVE_CA_ENDPOINT: process.env.REACT_APP_REMOVE_CA_ENDPOINT,

    REQUEST_ACCESS_ENDPOINT: process.env.REACT_APP_REQUEST_ACCESS_ENDPOINT,

    GET_COMBINED_IDENTITIES_ENDPOINT:
        process.env.REACT_APP_GET_COMBINED_IDENTITIES_ENDPOINT,

    COMBINE_IDENTITIES_ENDPOINT:
        process.env.REACT_APP_COMBINE_IDENTITIES_ENDPOINT,

    DELETE_COMBINED_IDENTITY_ENDPOINT:
        process.env.REACT_APP_DELETE_COMBINED_IDENTITY_ENDPOINT,

    TOGGLE_COMBINED_IDENTITY_ENDPOINT:
        process.env.REACT_APP_TOGGLE_COMBINED_IDENTITY_ENDPOINT,

    VAULT_ADDR_SUBDOMAIN: process.env.REACT_APP_VAULT_ADDR_SUBDOMAIN,

    VAULT_LOGIN_ENDPOINT: process.env.REACT_APP_VAULT_LOGIN,

    VAULT_DOMAIN: {
        MEDICAL: process.env.REACT_APP_VAULT_DOMAIN_MEDICAL,
        MANUFACTURER: process.env.REACT_APP_VAULT_DOMAIN_MANUFACTURER,
    },

    VAULT_FULL_DECRYPT_ENDPOINT:
        process.env.REACT_APP_VAULT_FULL_DECRYPT_ENDPOINT,
});
