module.exports = Object.freeze({
    RETRIEVE_LOG_INIT_REQUEST: "RETRIEVE_LOG_INIT_REQUEST",
    RETRIEVE_LOG_INIT_SUCCESS: "RETRIEVE_LOG_INIT_SUCCESS",
    RETRIEVE_LOG_INIT_FAILURE: "RETRIEVE_LOG_INIT_FAILURE",

    RETRIEVE_LOGS_REQUEST: "RETRIEVE_LOGS_REQUEST",
    RETRIEVE_LOGS_SUCCESS: "RETRIEVE_LOGS_SUCCESS",
    RETRIEVE_LOGS_FAILURE: "RETRIEVE_LOGS_FAILURE",

    RETRIEVE_EXTRA_LOGS_REQUEST: "RETRIEVE_EXTRA_LOGS_REQUEST",
    RETRIEVE_EXTRA_LOGS_SUCCESS: "RETRIEVE_EXTRA_LOGS_SUCCESS",
    RETRIEVE_EXTRA_LOGS_FAILURE: "RETRIEVE_EXTRA_LOGS_FAILURE",

    SYNC_AUDITS_REQUEST: "SYNC_AUDITS_REQUEST",
    SYNC_AUDITS_SUCCESS: "SYNC_AUDITS_SUCCESS",
    SYNC_AUDITS_FAILURE: "SYNC_AUDITS_FAILURE",
});
