module.exports = Object.freeze({
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",

  REFRESHING_TOKEN_REQUEST: "REFRESHING_TOKEN_REQUEST",
  REFRESHING_TOKEN_SUCCESS: "REFRESHING_TOKEN_SUCCESS",

  LOGIN_WITH_VAULT_REQUEST: "LOGIN_WITH_VAULT_REQUEST",
  LOGIN_WITH_VAULT_SUCCESS: "LOGIN_WITH_VAULT_SUCCESS",
  LOGIN_WITH_VAULT_FAILURE: "LOGIN_WITH_VAULT_FAILURE",
});
