module.exports = Object.freeze({
    REQUEST_ACCESS_REQUEST: "REQUEST_ACCESS_REQUEST",
    REQUEST_ACCESS_SUCCESS: "REQUEST_ACCESS_SUCCESS",
    REQUEST_ACCESS_FAILURE: "REQUEST_ACCESS_FAILURE",

    SYNC_WITH_BC_CLIENT_REQUESTS_REQUEST:
        "SYNC_WITH_BC_CLIENT_REQUESTS_REQUEST",
    SYNC_WITH_BC_CLIENT_REQUESTS_SUCCESS:
        "SYNC_WITH_BC_CLIENT_REQUESTS_SUCCESS",
    SYNC_WITH_BC_CLIENT_REQUESTS_FAILURE:
        "SYNC_WITH_BC_CLIENT_REQUESTS_FAILURE",

    SYNC_WITH_BC_CLIENT_EXTRA_REQUESTS_REQUEST:
        "SYNC_WITH_BC_CLIENT_EXTRA_REQUESTS_REQUEST",
    SYNC_WITH_BC_CLIENT_EXTRA_REQUESTS_SUCCESS:
        "SYNC_WITH_BC_CLIENT_EXTRA_REQUESTS_SUCCESS",
    SYNC_WITH_BC_CLIENT_EXTRA_REQUESTS_FAILURE:
        "SYNC_WITH_BC_CLIENT_EXTRA_REQUESTS_FAILURE",

    GET_COMBINED_IDENTITIES_REQUEST: "GET_COMBINED_IDENTITIES_REQUEST",
    GET_COMBINED_IDENTITIES_SUCCESS: "GET_COMBINED_IDENTITIES_SUCCESS",
    GET_COMBINED_IDENTITIES_FAILURE: "GET_COMBINED_IDENTITIES_FAILURE",

    COMBINE_IDENTITIES_REQUEST: "COMBINE_IDENTITIES_REQUEST",
    COMBINE_IDENTITIES_SUCCESS: "COMBINE_IDENTITIES_SUCCESS",
    COMBINE_IDENTITIES_FAILURE: "COMBINE_IDENTITIES_FAILURE",

    DELETE_COMBINED_IDENTITY_REQUEST: "DELETE_COMBINED_IDENTITY_REQUEST",
    DELETE_COMBINED_IDENTITY_SUCCESS: "DELETE_COMBINED_IDENTITY_SUCCESS",
    DELETE_COMBINED_IDENTITY_FAILURE: "DELETE_COMBINED_IDENTITY_FAILURE",

    TOGGLE_COMBINED_IDENTITY_REQUEST: "TOGGLE_COMBINED_IDENTITY_REQUEST",
    TOGGLE_COMBINED_IDENTITY_SUCCESS: "TOGGLE_COMBINED_IDENTITY_SUCCESS",
    TOGGLE_COMBINED_IDENTITY_FAILURE: "TOGGLE_COMBINED_IDENTITY_FAILURE",

    USER_VALIDATION_REQUEST: "USER_VALIDATION_REQUEST",
    USER_VALIDATION_SUCCESS: "USER_VALIDATION_SUCCESS",
    USER_VALIDATION_FAILURE: "USER_VALIDATION_FAILURE",

    GET_DATA_REQUEST: "GET_DATA_REQUEST",
    GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
    GET_DATA_FAILURE: "GET_DATA_FAILURE",

    FULL_DECRYPT_WITH_VAULT_REQUEST: "FULL_DECRYPT_WITH_VAULT_REQUEST",
    FULL_DECRYPT_WITH_VAULT_SUCCESS: "FULL_DECRYPT_WITH_VAULT_SUCCESS",
    FULL_DECRYPT_WITH_VAULT_FAILURE: "FULL_DECRYPT_WITH_VAULT_FAILURE",
});
