module.exports = Object.freeze({
  FETCH_ORGANIZATIONS_LIST_REQUEST: "FETCH_ORGANIZATIONS_LIST_REQUEST",
  FETCH_ORGANIZATIONS_LIST_SUCCESS: "FETCH_ORGANIZATIONS_LIST_SUCCESS",
  FETCH_ORGANIZATIONS_LIST_FAILURE: "FETCH_ORGANIZATIONS_LIST_FAILURE",

  APPEND_NEW_NOTIFICATION: "APPEND_NEW_NOTIFICATION",
  UI_RECEIVED_NOTIFICATION: "UI_RECEIVED_NOTIFICATION",

  SYNC_WITH_BC_REQUEST: "SYNC_WITH_BC_REQUEST",
  SYNC_WITH_BC_SUCCESS: "SYNC_WITH_BC_SUCCESS",
  SYNC_WITH_BC_FAILURE: "SYNC_WITH_BC_FAILURE",
});
