---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orderer-ministry-0-manufacturer-env
data:
  FABRIC_CFG_PATH: /var/hyperledger/fabric/config/manufacturer
  FABRIC_LOGGING_SPEC: DEBUG # debug:cauthdsl,policies,msp,common.configtx,common.channelconfig=info
  ORDERER_GENERAL_LISTENADDRESS: 0.0.0.0
  ORDERER_GENERAL_LISTENPORT: "6050"
  ORDERER_GENERAL_LOCALMSPID: OrdererMSP
  ORDERER_GENERAL_LOCALMSPDIR: /var/hyperledger/fabric/organizations/ordererOrganizations/ministry-of-health/orderers/orderer-ministry-0/msp
  ORDERER_GENERAL_TLS_ENABLED: "true"
  ORDERER_GENERAL_TLS_CERTIFICATE: /var/hyperledger/fabric/organizations/ordererOrganizations/ministry-of-health/orderers/orderer-ministry-0/tls/signcerts/cert.pem
  ORDERER_GENERAL_TLS_ROOTCAS: /var/hyperledger/fabric/organizations/ordererOrganizations/ministry-of-health/orderers/orderer-ministry-0/tls/cacerts/ca-ministry-of-health.pem
  ORDERER_GENERAL_TLS_PRIVATEKEY: /var/hyperledger/fabric/organizations/ordererOrganizations/ministry-of-health/orderers/orderer-ministry-0/tls/keystore/server.key
  ORDERER_GENERAL_BOOTSTRAPMETHOD: none
  ORDERER_FILELEDGER_LOCATION: /var/hyperledger/fabric/manufacturer/data/orderer-ministry-0/manufacturer
  ORDERER_CONSENSUS_WALDIR: /var/hyperledger/fabric/manufacturer/data/orderer-ministry-0/etcdraft/wal/manufacturer
  ORDERER_CONSENSUS_SNAPDIR: /var/hyperledger/fabric/manufacturer/data/orderer-ministry-0/etcdraft/wal/manufacturer
  ORDERER_OPERATIONS_LISTENADDRESS: 0.0.0.0:8443
  ORDERER_ADMIN_LISTENADDRESS: 0.0.0.0:9443
  TZ: "Europe/Athens"
  ORDERER_METRICS_PROVIDER: "prometheus"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: orderer-ministry-0-manufacturer
  name: orderer-ministry-0-manufacturer
spec:
  ports:
    - name: general
      port: 6050
      protocol: TCP
    - name: operations
      port: 8443
      protocol: TCP
    - name: admin
      port: 9443
      protocol: TCP
  selector:
    app: orderer-ministry-0-manufacturer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: orderer-ministry-0-manufacturer
  name: orderer-ministry-0-manufacturer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer-ministry-0-manufacturer
  template:
    metadata:
      labels:
        app: orderer-ministry-0-manufacturer
    spec:
      containers:
        - name: main
          envFrom:
            - configMapRef:
                name: orderer-ministry-0-manufacturer-env
          image: hyperledger/fabric-orderer:{{FABRIC_VERSION}}
          ports:
            - containerPort: 6050
            - containerPort: 8443
            - containerPort: 9443
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config/manufacturer
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: ministry-of-health-disk-claim
        - name: fabric-config
          configMap:
            name: ministry-of-health-manufacturer-config
